<?php

/**
 * @file
 * Allows generation of IIIF objects
 */


/**
 * Implements hook_menu().
 */
function islandora_sc_manifest_menu() {

  return array(
    'islandora/object/%islandora_object/manage/scmanifest' => array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('iiif_generate', 2),
      'type' => MENU_LOCAL_TASK,
      'title' => 'IIIF Generation',
      'access callback' => 'iiif_generation_access',
      'access arguments' => array(2),
      'file' => 'includes/callbacks.inc',
    ),

    'admin/islandora/tools/sc_manifest' => array(
      'title' => 'Islandora IIIF Generator',
      'description' => 'Configure settings for Islandora IIIF Generation module',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_sc_manifest_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    )

  );
}

function iiif_generation_access($fedora_object) {
  $allowedModels = array(
    'islandora:bookCModel', 
    'islandora:sp_basic_image',
    'islandora:sp_large_image_cmodel',
    'islandora:collectionCModel',
    'islandora:compoundCModel',
  );
  $result = !empty(array_intersect($fedora_object->models, $allowedModels));
  return !empty($result) && user_is_logged_in();
}
